services:
  bookflix-frontend:
    image: satvi4/bookflix-frontend:latest
    container_name: bookflix-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      my-net:
    restart: always
    volumes:
      - /frontend:/usr/share/nginx/html/templates

  bookflix-backend:
    image: satvi4/bookflix-backend:latest
    container_name: bookflix-backend
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      my-net:
    # Using Docker volume for persisting logs
    volumes:
      - /logs:/booklogs:rw
      - /frontend:/templates
  
networks:
  my-net:

volumes:
  logs:
  frontend: