services:
  bookflix-frontend:
    image: satvi4/bookflix-frontend:latest
    container_name: bookflix-frontend
    # Keep stdin_open because we don't want this container to exit immediately which it
    # otherwise would have because there's no foreground processes
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      my-net:
    restart: always

  bookflix-backend:
    image: satvi4/bookflix-backend:latest
    container_name: bookflix-backend
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      my-net:
    # Using Docker volume for persisting logs
    # ./backend/logs refers to the path /home/backend/logs on the host machine
    # and we're linking it to logs folder on the container machine
    volumes:
      - /logs:/backend/logs
  
networks:
  my-net:

volumes:
  logs:
   name: logs
  Frontend:
   name: Frontend