- name: Deploy docker images
  hosts: localhost
  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Pull the Docker images specifed in docker-compose
      command: docker-compose -f docker-compose.yml pull

    - name: Create containers for the pulled Docker images
      command: docker-compose -f docker-compose.yml up -d --force-recreate

    - name: Prune the dangling Docker images
      command: docker image prune --force