- name: Deploy docker images
  hosts: localhost
  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Create containers for the pulled Docker images
      command: docker-compose create

    - name: Prune the dangling Docker images
      command: docker image prune --force