spring.main.allow-circular-references:
  true

spring:
  application:
    name: bookflix
  profiles:
    active: 
  security:
    oauth2: 
      client:
        registration:
          github:
            client-id: Iv1.1b5dd7e22c0cf8cd
            client-secret: 8362896850feab096200d22d21980cd5d5472e84
          google:
            client-id: 465566953017-hop8k32gafr7n0pv2ffvsj7m96a2mtf3.apps.googleusercontent.com
            client-secret: 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

  data:
    cassandra:
      keyspace-name: main
      username: XZSvKsyAKezLUIaFzAPCWhvs
      password: D2R_GY6iSXbcSACPYPQ3NP6Zk.Zm+852y06ueciJuQHRQI8+,nzl9-GM72fP+QJ8+QlM6qrZq4wXj5qbS9+dAd03Hd-4vwZWptahTnIa.H.EQ72qX_SSuW+UjTJYOkUQ
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: 574d9311-ca2a-4db0-9b45-3024546f25ab-1
    region: us-east1
    keyspace: main
    application.token: AstraCS:XZSvKsyAKezLUIaFzAPCWhvs:5bb6f467b50ee8b5b8d029024ebb98344b6962e6bd5cdf7aa16be9f9f6fd42a0

server:
  port : 9090

logging:
  file:
    name: ./booklogs/booklogs.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M %msg%n"
  level:
    -root: ERROR
    -com.example.bookflix: INFO